### ISSUE TITLE
Configure loader with additional modifiers

### ISSUE THREAD

**Issue by nik-kor** [alfa-bank-dev/bem-css-loader#7]
The problem is that some modifiers aren't written as dependencies to block. So loader didn't get them.

Something like this

```js
require('bem-css-loader?add-mods=_has-clear,_theme_black!./plate.css');
```

TODO: think about simpler query format

**Comment by nik-kor** [comment]
After some research we decided not to configure loader this way. The better decision is to use additional levels and set up deps there.

**Comment by nik-kor** [comment]
@ziimir

**Comment by awinogradov** [comment]
:+1:
